# Generated by Django 5.0.6 on 2024-07-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_proyecto_user_profile_alter_budgetitem_valor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='valor',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
