# Generated by Django 5.0.6 on 2024-08-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_remove_proyecto_user_profile_alter_budgetitem_valor_and_more'),
        ('solicitud', '0010_alter_cotizacion_file_coti_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolictud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyecto.budgetitem')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitud.solicitud')),
            ],
        ),
    ]
