# Generated by Django 5.0.6 on 2024-08-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_itemsolictud'),
        ('solicitud', '0010_alter_cotizacion_file_coti_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSolicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('unidad', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='proyecto.budgetitem')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Item solicitud',
                'verbose_name_plural': 'Items solicitud',
            },
        ),
        migrations.DeleteModel(
            name='ItemSolictud',
        ),
    ]
