# Generated by Django 5.0.6 on 2024-07-30 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_solicitud_cotizacion_aceptada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(max_length=18),
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula_ruc', models.CharField(max_length=13)),
                ('tipo_compra', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('no_contr_fac', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('url_contr_fac', models.URLField(blank=True, default=None, null=True)),
                ('forma_tipo_pago', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('certi_banco', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulario', to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
            },
        ),
    ]
