# Generated by Django 5.0.6 on 2024-07-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_formulario_correo_formulario_nombre_banco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_coti',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='link_coti',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='no_coti',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='proveedor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='certi_banco',
            field=models.FileField(blank=True, default=None, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='codigo',
            field=models.CharField(max_length=21),
        ),
    ]
