# Generated by Django 5.0.6 on 2024-07-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0006_alter_solicitud_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulario',
            old_name='forma_tipo_pago',
            new_name='forma_pago',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='no_contr_fac',
            new_name='no_compra',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='url_contr_fac',
        ),
        migrations.AddField(
            model_name='formulario',
            name='file_compra',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contr-fac/'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tiempo',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_acuerdo',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo_pago',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
