# Generated by Django 5.0.6 on 2024-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0007_rename_forma_tipo_pago_formulario_forma_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='link_coti',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='file_coti',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cotis/'),
        ),
    ]
