# Generated by Django 5.0.6 on 2024-08-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0008_remove_cotizacion_link_coti_cotizacion_file_coti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='file_coti',
            field=models.FileField(blank=True, default=None, null=True, upload_to='coti/<built-in method now of type object at 0x00007FFBD855AFD0>'),
        ),
    ]
