# Generated by Django 5.0.6 on 2024-08-04 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0009_alter_cotizacion_file_coti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='file_coti',
            field=models.FileField(blank=True, default=None, null=True, upload_to='coti/<built-in method now of type object at 0x00007FFBF845AFD0>'),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='solicitud.solicitud')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
