# Generated by Django 5.0.6 on 2024-08-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0010_alter_cotizacion_file_coti_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='file_coti',
            field=models.FileField(blank=True, default=None, null=True, upload_to='cotis/2024-08-04_21-38-07'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='certi_banco',
            field=models.FileField(blank=True, default=None, null=True, upload_to='certificados/2024-08-04_21-38-07'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='file_compra',
            field=models.FileField(blank=True, default=None, null=True, upload_to='contr-fac/2024-08-04_21-38-07'),
        ),
    ]
